### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jalilTaghinezhad** [GoodieBag/Pinview#33]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.goodiebag.pinview.Pinview.onTextChanged(Pinview.java:73)
       at android.widget.TextView.sendOnTextChanged(TextView.java:10959)
       at android.widget.TextView.setText(TextView.java:6384)
       at android.widget.TextView.setText(TextView.java:6184)
       at android.widget.EditText.setText(EditText.java:146)
       at android.widget.TextView.setText(TextView.java:6141)
       at sefryek.com.hamrahbanksepah.activityActivation.ReceiveCodeActivity.clearPinViewChild(ReceiveCodeActivity.java:49)
       at sefryek.com.hamrahbanksepah.activityActivation.ReceiveCodeActivity.setFonts(ReceiveCodeActivity.java)
       at sefryek.com.hamrahbanksepah.activityActivation.ReceiveCodeActivity$configResendCode$1.invoke(ReceiveCodeActivity.java:27)
       at sefryek.com.hamrahbanksepah.activityActivation.ReceiveCodeActivity$configResendCode$1.invoke(ReceiveCodeActivity.java:27)
       at sefryek.com.hamrahbanksepah.activityActivation.ReceiveCodeActivity$configResendCode$1.invoke(ReceiveCodeActivity.java:2)
       at sefryek.com.hamrahbanksepah.activityActivation.ReceiveCodeActivity$configResendCode$1.invoke(ReceiveCodeActivity.java:2)
       at sefryek.com.hamrahbanksepah.Extention.GroupKt$sam$i$android_view_View_OnClickListener$0.onClick(GroupKt.java:2)
       at android.view.View.performClick(View.java:7339)
       at android.widget.TextView.performClick(TextView.java:14222)
       at android.view.View.performClickInternal(View.java:7305)
       at android.view.View.access$3200(View.java:846)
       at android.view.View$PerformClick.run(View.java:27788)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by daupawar** [comment]
I have the same issue on MIUI devices

**Comment by basilbattikhi** [comment]
After traversing the code, It's not about MIUI, its all about if you have 5 fields you need to fill All 5 fields otherwise it will crash
